language: python
dist: xenial

branches:
  only:
    - master

python:
  - 3.6
  - 3.7
  - 3.8

jobs:
  include:
    - stage: "Check"
      python: 3.7
      script: scripts/check
    - stage: "Docs"
      python: 3.7
      scripts: scripts/docs

script:
  - scripts/test
