language: python
dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

jobs:
  include:
    - stage: "Check"
      name: "Lint"
      python: 3.7
      script:
        - mypy tartiflette_starlette
        - flake8 tartiflette_starlette tests setup.py

before_install:
  - sudo apt-get install cmake flex bison
  - pip install -U pip

script:
  - pytest

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    # deploy only once
    python: "3.7"
