site_name: tartiflette-asgi
site_description: ASGI support for the Tartiflette Python GraphQL engine

theme:
  name: material

repo_name: tartiflette/tartiflette-asgi
repo_url: https://github.com/tartiflette/tartiflette-asgi
edit_uri: ""

nav:
  - Introduction: "index.md"

markdown_extensions:
  - codehilite:
      guess_lang: false
