resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: florimondmanca/azure-pipelines-templates
      ref: refs/heads/dev-3.1

trigger:
  - master

pr:
  - master

variables:
  CI: true
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.cache/pip

jobs:
  - template: job--python-check.yml@templates
    parameters:
      pythonVersion: "3.8"

  - job: Docs
    steps:
      - template: step--python-install.yml@templates
        parameters:
          pythonVersion: "3.8"
      - bash: scripts/docs
        displayName: "Docs"

      - bash: scripts/test
        displayName: "Test Py38"

  - template: job--python-test.yml@templates
    parameters:
      jobs:
        py36: null
        py37: null
        py38:
          coverage: true
